### ISSUE TITLE
Make Electron open "Build path" on successful build

### ISSUE THREAD

**Issue by sethdavis512** [sethdavis512/pseudopia-app#11]
**Describe the solution you'd like**
Make Electron open the "Build path" in Finder after a successful build.

**Bonus Points**
Add a toggle/checkbox to allow the user to choose whether they want to open folder after build.

**Comment by jvmoreira** [comment]
Hey, nice project! I've just created a PR for this issue, hope it helps :D

Also, I was thinking... What if, instead of a checkbox, the `Open Build Path` was an action button right next to the `Build` one?
Or else inside the `Successfully compiled!` notification?

What do you think?

**Comment by sethdavis512** [comment]
First of all, thank you very much @jvmoreira for your contributions! 

I do think the `Open Build Path` button is a good idea and definitely worth exploring. I'm leaning towards having it sit right next to the `Build` button instead of in the notification.

Is the `Open Build Path` button something you are wanting to contribute? I don't want to take away from anyone's contribution...

**Comment by jmmendivil** [comment]
> I do think the `Open Build Path` button is a good idea and definitely worth exploring. I'm leaning towards having it sit right next to the `Build` button instead of in the notification.

I like the idea of the `Open Build Path` button as @jvmoreira says, but next the `Build Path` _input_ instead the `Build` _button_, so the purpose of that button would be to help the user open the _textual path_ on finder. That way we can still use the toggle/checkbox like a config (next the `Build button`) as the initial idea.

**Comment by jmmendivil** [comment]
Maybe this is not the way you would like to go, but I just wanted to show you the visual proposal of the previous comment

<img width="409" alt="image" src="https://user-images.githubusercontent.com/1274534/95667948-b3ef3200-0b32-11eb-93af-7e54a826a6fb.png">

**Comment by jvmoreira** [comment]
That's actually pretty good @jmmendivil. I think it would work well.

**Comment by jmmendivil** [comment]
Thanks, @jvmoreira. I can add it, once it gets @sethdavis512 feedback.

**Comment by sethdavis512** [comment]
October has been a crazy month! I will follow up soon.

**Comment by sethdavis512** [comment]
I like this idea @jmmendivil - lets move forward with it!
