### ISSUE TITLE
Handle template errors

### ISSUE THREAD

**Issue by sethdavis512** [sethdavis512/pseudopia-app#12]
**Describe the bug**
If a template doesn't exist for some reason, Electron throws an alert. Pseudopia should handle errors like this with a notification in the top right corner.

**To Reproduce**
1. Add a template using the "Set Base Component Path" button
2. Change the newly set template name to something different.
3. Click "Build"

**Expected behavior**
If template fails to load, a notification should pop up in the top right corner with an error explaining the failure.

**Screenshots**
![image](https://user-images.githubusercontent.com/3208705/94865507-586ec700-0403-11eb-9d23-68b251d73045.png)

**Additional context**
Once the error is wired up, it should look similar to:
![image](https://user-images.githubusercontent.com/3208705/94865861-ef3b8380-0403-11eb-9f54-17d268a3ad94.png)

**Comment by sandy9808** [comment]
I will try my best to resolve the error.

**Comment by sethdavis512** [comment]
No longer an issue.
